# Generated by Django 3.0.8 on 2020-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('big_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('bullet_1', models.TextField()),
                ('bullet_2', models.TextField()),
                ('bullet_3', models.TextField()),
                ('bullet_4', models.TextField()),
                ('approach', models.TextField()),
            ],
        ),
    ]
