# Generated by Django 3.0.8 on 2020-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200717_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='specific_design_drop',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
