# Generated by Django 3.0.8 on 2020-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_specific_design_drop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolios'},
        ),
    ]
