# Generated by Django 3.0.8 on 2020-07-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_item_big_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='big_description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
